// <auto-generated />
using Fleet.Orchestrator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Fleet.Orchestrator.Migrations;

[DbContext(typeof(OrchestratorDbContext))]
[Migration("20260419000000_AddWelcomeSentAt")]
partial class AddWelcomeSentAt
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
