// <auto-generated />
using System;
using Fleet.Orchestrator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fleet.Orchestrator.Migrations
{
    [DbContext(typeof(OrchestratorDbContext))]
    [Migration("20260410000000_AddSuppressToolMessages")]
    partial class AddSuppressToolMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Orchestrator.Data.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("AutoMemoryEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CodexSandboxMode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Effort")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("GroupDebounceSeconds")
                        .HasColumnType("int");

                    b.Property<string>("GroupListenMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("mention");

                    b.Property<int?>("HostPort")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JsonSchema")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxTurns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PermissionMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("acceptEdits");

                    b.Property<bool>("PrefixMessages")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProactiveIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("claude");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("ShowStats")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SuppressToolMessages")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TelegramSendOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TtsServiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("WorkDir")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("/workspace");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentEnvRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("EnvKeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "EnvKeyName")
                        .IsUnique();

                    b.ToTable("agent_env_refs", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("InstructionId")
                        .HasColumnType("int");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructionId");

                    b.HasIndex("AgentId", "InstructionId")
                        .IsUnique();

                    b.HasIndex("AgentId", "LoadOrder");

                    b.ToTable("agent_instructions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentMcpEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("McpName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "McpName")
                        .IsUnique();

                    b.ToTable("agent_mcp_endpoints", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "NetworkName")
                        .IsUnique();

                    b.ToTable("agent_networks", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "ProjectName")
                        .IsUnique();

                    b.ToTable("agent_projects", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTelegramGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "GroupId")
                        .IsUnique();

                    b.ToTable("agent_telegram_groups", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "UserId")
                        .IsUnique();

                    b.ToTable("agent_telegram_users", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "ToolName")
                        .IsUnique();

                    b.ToTable("agent_tools", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("instructions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.InstructionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("InstructionId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InstructionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("instruction_versions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.ProjectContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("project_contexts", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.ProjectContextVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProjectContextId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectContextId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("project_context_versions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.WorkflowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskQueue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.WorkflowDefinitionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("workflow_definition_versions", (string)null);
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentEnvRef", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("EnvRefs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentInstruction", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("Instructions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleet.Orchestrator.Data.Instruction", "Instruction")
                        .WithMany("AgentInstructions")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentMcpEndpoint", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("McpEndpoints")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentNetwork", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("Networks")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentProject", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("Projects")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTelegramGroup", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("TelegramGroups")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTelegramUser", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("TelegramUsers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.AgentTool", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Agent", "Agent")
                        .WithMany("Tools")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.InstructionVersion", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.Instruction", "Instruction")
                        .WithMany("Versions")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.ProjectContextVersion", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.ProjectContext", "ProjectContext")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectContext");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.WorkflowDefinitionVersion", b =>
                {
                    b.HasOne("Fleet.Orchestrator.Data.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.Agent", b =>
                {
                    b.Navigation("EnvRefs");

                    b.Navigation("Instructions");

                    b.Navigation("McpEndpoints");

                    b.Navigation("Networks");

                    b.Navigation("Projects");

                    b.Navigation("TelegramGroups");

                    b.Navigation("TelegramUsers");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.Instruction", b =>
                {
                    b.Navigation("AgentInstructions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.ProjectContext", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Fleet.Orchestrator.Data.WorkflowDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
