// <auto-generated />
using Fleet.Orchestrator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Fleet.Orchestrator.Migrations;

[DbContext(typeof(OrchestratorDbContext))]
[Migration("20260503000000_AddAgentProjectAccess")]
partial class AddAgentProjectAccess
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
